server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    # 每隔10s扫描服务列表，移除失效服务
    eviction-interval-timer-in-ms: 10000
spring:
  application:
    name: eurka-server
