app:
  id: SampleApp
apollo:
  meta: http://localhost:8080
server:
  port: 8621
spring:
  application:
    name: service-sdk
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.client.serviceUrl.defaultZone}
