app:
  id: SampleApp
apollo:
  meta: http://localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.client.serviceUrl.defaultZone}
server:
  port: 8019
spring:
  application:
    name: service-zuul
zuul:
  routes:
    sdk-service:
      path: /sdk/**
      serviceId: service-sdk